# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
R:
  - 3.5.3
sudo: false
cache: packages

r_packages:
  - covr


matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
